# Generated by Django 3.0.8 on 2020-07-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_auto_20200731_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='nonVeg',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='veg',
            field=models.BooleanField(),
        ),
    ]
